# Generated by Django 5.0.1 on 2024-01-10 00:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('lm', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=130)),
                ('preco', models.FloatField(max_length=10)),
                ('link', models.CharField(max_length=250)),
                ('avaliacoes', models.IntegerField()),
                ('media_avaliacoes', models.FloatField(max_length=4)),
                ('data_produto', models.DateTimeField(default=datetime.datetime.now)),
                ('foto', models.ImageField(blank=True, upload_to='')),
                ('info_produto', models.CharField(max_length=1000)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
