# Generated by Django 5.0.1 on 2024-01-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_produto',
            field=models.DateField(auto_now_add=True),
        ),
    ]
