# Generated by Django 5.0.1 on 2024-01-16 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_loja1_loja2_loja3_alter_produto_data_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja2',
            name='tipo_produto',
        ),
    ]
