# Generated by Django 5.0.1 on 2024-01-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_remove_loja2_tipo_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja2',
            name='tipo_produto',
            field=models.CharField(choices=[('E', 'Eletrônico'), ('M', 'Moda'), ('A', 'Alimento'), ('O', 'Outros'), ('J', 'Jogos')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loja1',
            name='tipo_produto',
            field=models.CharField(choices=[('E', 'Eletrônico'), ('M', 'Moda'), ('A', 'Alimento'), ('O', 'Outros'), ('J', 'Jogos')], max_length=1),
        ),
        migrations.AlterField(
            model_name='loja3',
            name='tipo_produto',
            field=models.CharField(choices=[('E', 'Eletrônico'), ('M', 'Moda'), ('A', 'Alimento'), ('O', 'Outros'), ('J', 'Jogos')], max_length=1),
        ),
    ]
