# Generated by Django 5.0.1 on 2024-02-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_loja2_tipo_produto_alter_loja1_tipo_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testes',
            fields=[
                ('lm', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=130)),
            ],
        ),
    ]
