# Generated by Django 5.0.1 on 2024-02-02 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_testes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testes',
            old_name='lm',
            new_name='code',
        ),
    ]
